### ISSUE TITLE
Add the ability to log in with a premium account

### ISSUE THREAD

**Issue by somepersononthenet** [Alphaverers/AlphaverLauncherRecreation#10]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to log in with a premium account so for example you dont have to type your password on erd's lilypad server

**Additional context**
would be cool

**Comment by Gnawmon** [comment]
maybe idk

**Comment by unnaturalistic** [comment]
This might be added, although the launch time might get increased and not be controllable; the other thing to consider is **us**, it is hard to add this and we might actually need to add support for mojang accounts if some are not migrated 
This will be in our plans for V4 but i wont guarantee it.

**Comment by Gnawmon** [comment]
nah it is not hard

**Comment by Gnawmon** [comment]
Nope, I can't create an Azure account for Microsoft authentication. 

Until someone gives access to an Azure account it isn't possible.

**Comment by unnaturalistic** [comment]
as i said
hard
