### ISSUE TITLE
Norton antivirus says this is a virus

### ISSUE THREAD

**Issue by MayhemForge** [Alphaverers/AlphaverLauncherRecreation#11]
When I download the launcher zip and extract the files into a folder Norton antivirus deletes the exe and says that it was a virus. why does it say this, how do I fix this, and if it is a virus, how do I remove the virus from the file?

**Comment by Gnawmon** [comment]
It is open source there is little chance that it could be a virus.

Check [this](https://support.norton.com/sp/en/us/home/current/solutions/v3672136)
