### ISSUE TITLE
Microsoft accounts integration

### ISSUE THREAD

**Issue by unnaturalistic** [Alphaverers/AlphaverLauncherRecreation#13]

**Comment by unnaturalistic** [comment]
i mean...eh?

**Comment by Vincent392** [comment]
As long as we can still have offline. And also Mojang till September. Aka code a timebomb with the Mojang login button 
![2023_03_11_0vc_Kleki.png](https://github.com/Alphaverers/AlphaverLauncherRecreation/assets/90470156/df324a42-64a8-4866-adfc-8d0532d62f42)

**Comment by unnaturalistic** [comment]
yeah we would still have offline
