### ISSUE TITLE
Addnew mods

### ISSUE THREAD

**Issue by unnaturalistic** [Alphaverers/AlphaverLauncherRecreation#15]
Yeah..
also thanks to vlad for giving this list!
![image](https://github.com/Alphaverers/AlphaverLauncherRecreation/assets/93143883/1a2902e6-97e7-4af8-abc2-3e47cee47d5e)

**Comment by Vincent392** [comment]
oh boy PL(-L).
I do not want to be reminded of that.
oh and the preview version could have TB8-InfTimeTest- wait fuck it's down what happened to it?
