### ISSUE TITLE
Breaking News!!!!! R4 IS RELEASED

### ISSUE THREAD

**Issue by yarik303** [Alphaverers/AlphaverLauncherRecreation#16]
add r4
cuz why not lol

**Comment by Vincent392** [comment]
It's not going to be added.
So yay.
Even at that how the fuck are you meant to download a 100MB+ .jar file in a torrent?

**Comment by yarik303** [comment]
i downloaded in a few minutes idk about u. i have heard smbdy on the server reuploaded it. and i have downloaded the torrent files . if u need i can send

**Comment by Gnawmon** [comment]
This project is no longer maintained. Don't expect any new stuff
