### ISSUE TITLE
Discord RPC (DRPC)

### ISSUE THREAD

**Issue by Vincent392** [Alphaverers/AlphaverLauncherRecreation#7]
---
name: Discord RPC
about: You heard me add discord RPC.
title: 'Discord RPC (DRPC)'
labels: enhancement
assignees: 'Gnawmon'

---

**Is your feature request related to a problem? Please describe.**
no

**Additional context**
I Can say this from attempting it myself adding RPC is hard on java but on C# Its fine probably. and having it there would be nice.
(I dono what it would display as in discord with the name)

**Comment by Gnawmon** [comment]
i will take a look at it

**Comment by Vincent392** [comment]
Now that it is implemented...
It just needs to ofc.
Be added to a public build and this needs to be closed.

**Comment by Gnawmon** [comment]
It will be included in the next build.
