### ISSUE TITLE
Can't launch game

### ISSUE THREAD

**Issue by somepersononthenet** [Alphaverers/AlphaverLauncherRecreation#8]
**Describe the bug**
Launcher crashes when opening game.

**To Reproduce**
1. Open the launcher
2. Click play

**Expected behavior**
You should be able to play

**Screenshots**
Ehhhhhhhh...

**OS**
Windows 11 22H2
**Java Version**
¯\_(ツ)_/¯

**Additional context**
nah

**Comment by somepersononthenet** [comment]
well it seems like you have to compile a debug build to get it working, so im good

**Comment by somepersononthenet** [comment]
wait nope, game still wont open

**Comment by Gnawmon** [comment]
Yeah, I'm aware of this. In the next build, I will replace the launcher library to fix this.

**Comment by unnaturalistic** [comment]
we drop kicked cmdlib
expect fixes

**Comment by unnaturalistic** [comment]
fixed in V3
