### ISSUE TITLE
cant play game

### ISSUE THREAD

**Issue by somepersononthenet** [Alphaverers/AlphaverLauncherRecreation#9]
**Describe the bug**
i cant play the game

**To Reproduce**
click play

**Expected behavior**
i can play

**Screenshots**

**OS**
win 11
**Java Version**
java 17

**Additional context**
this is the second time

**Comment by somepersononthenet** [comment]
nvm just me being a dumbass

**Comment by Gnawmon** [comment]
:arg_fans:
